# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  name: 'Ubuntu_Pool'

variables:
  GO_INSTALL: '/usr/lib/go-1.12'

- script: |
    go version
    go env
  displayName: 'Checking Go installation'
  
- script: |
    go test -v ./...
  workingDirectory: $(Build.SourcesDirectory)/PaymentGateway
  displayName: 'Running all the cmd tests'
  
- script: |
    go build -v
  workingDirectory: $(Build.SourcesDirectory)/PaymentGateway
  displayName: 'Building Go Ipfs'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PaymentGateway/PaymentGateway'
    includeRootFolder: true
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: '$(Build.ArtifactStagingDirectory)/payment-gateway-$(Build.BuildId).7z'
    replaceExistingArchive: true
    verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PaymentGateway/PaymentGateway'
    includeRootFolder: true
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: '$(Build.ArtifactStagingDirectory)/payment-gateway-latest.7z'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'payment-gateway'
    publishLocation: 'Container'
