# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  name: 'Ubuntu_Pool'

#variables:
#  GO_INSTALL: '/usr/lib/go-1.12'

steps:
#- script: |
#    echo '##vso[task.setvariable variable=path]$(PATH):$(GO_INSTALL)/bin'
#  displayName: 'Setting Go installation'
  
- script: |
    go version
    go env
  displayName: 'Checking Go installation'
  
# - script: |
#     go test -v ./...
#   workingDirectory: $(Build.SourcesDirectory)/PaymentGateway
#   displayName: 'Running all the tests'
  
- script: |
    go build paidpiper.com/payment-gateway
  workingDirectory: $(Build.SourcesDirectory)/PaymentGateway
  displayName: 'Building Payment Gateway'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PaymentGateway/payment-gateway'
    includeRootFolder: true
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: '$(Build.ArtifactStagingDirectory)/payment-gateway-$(Build.BuildId).7z'
    replaceExistingArchive: true
    verbose: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PaymentGateway/payment-gateway'
    includeRootFolder: true
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: '$(Build.ArtifactStagingDirectory)/payment-gateway-latest.7z'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'payment-gateway'
    publishLocation: 'Container'
