# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- pp_master

variables:
   major: 1
   minor: 0

name: $(major).$(minor)$(Rev:.r)

strategy:
  matrix:
    linux:
      poolName: 'Ubuntu_Pool'
      vmImage:
      osName: 'linux'
      ext: ''
      addldflags: ''
    windows:
      poolName: 'Windows_Pool'
      vmImage:
      osName: 'windows'
      ext: ".exe"
      addldflags: '-ldflags -H=windowsgui'
    mac:
      poolName: 'Azure Pipelines'
      vmImage: 'macOS-10.14'
      osName: 'mac'
      ext: ''
      addldflags: ''


pool:
  name: $(poolName)
  vmImage: $(vmImage)

steps:
- task: GoTool@0
  inputs:
    version: '1.16.3'
  condition: eq(variables.osName, 'mac')

- script: |
    go version
    go env
  displayName: 'Checking Go installation'
  
- script: |
    go test -v ./... | true
  workingDirectory: $(Build.SourcesDirectory)/PaymentGateway
  displayName: 'Running all the tests'
  
- script: |
    go build -v -o payment-gateway$(ext) $(addldflags)  paidpiper.com/payment-gateway/cmd/main
  workingDirectory: $(Build.SourcesDirectory)/PaymentGateway
  displayName: 'Building Payment Gateway'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/PaymentGateway/payment-gateway$(ext)'
    includeRootFolder: true
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: '$(Build.ArtifactStagingDirectory)/payment-gateway-$(osName)-$(Build.BuildNumber).7z'
    replaceExistingArchive: true
    verbose: true

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(Build.SourcesDirectory)/PaymentGateway/payment-gateway$(ext)'
#    includeRootFolder: true
#    archiveType: '7z'
#    sevenZipCompression: 'ultra'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/payment-gateway-$(osName)-latest.7z'
#    replaceExistingArchive: true
#    verbose: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'payment-gateway'
    publishLocation: 'Container'
