// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ppsidechannel.proto

package ppsidechannel

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetUpPeerResponse_SetUpStatus int32

const (
	SetUpPeerResponse_PeerAlreadyExists           SetUpPeerResponse_SetUpStatus = 0
	SetUpPeerResponse_PeerAccountCreationRequired SetUpPeerResponse_SetUpStatus = 1
	SetUpPeerResponse_PeerAccountFundingRequired  SetUpPeerResponse_SetUpStatus = 2
)

var SetUpPeerResponse_SetUpStatus_name = map[int32]string{
	0: "PeerAlreadyExists",
	1: "PeerAccountCreationRequired",
	2: "PeerAccountFundingRequired",
}

var SetUpPeerResponse_SetUpStatus_value = map[string]int32{
	"PeerAlreadyExists":           0,
	"PeerAccountCreationRequired": 1,
	"PeerAccountFundingRequired":  2,
}

func (x SetUpPeerResponse_SetUpStatus) String() string {
	return proto.EnumName(SetUpPeerResponse_SetUpStatus_name, int32(x))
}

func (SetUpPeerResponse_SetUpStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{1, 0}
}

type SetUpPeerRequest struct {
	StellarAddress       string   `protobuf:"bytes,1,opt,name=stellarAddress,proto3" json:"stellarAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUpPeerRequest) Reset()         { *m = SetUpPeerRequest{} }
func (m *SetUpPeerRequest) String() string { return proto.CompactTextString(m) }
func (*SetUpPeerRequest) ProtoMessage()    {}
func (*SetUpPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{0}
}

func (m *SetUpPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUpPeerRequest.Unmarshal(m, b)
}
func (m *SetUpPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUpPeerRequest.Marshal(b, m, deterministic)
}
func (m *SetUpPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUpPeerRequest.Merge(m, src)
}
func (m *SetUpPeerRequest) XXX_Size() int {
	return xxx_messageInfo_SetUpPeerRequest.Size(m)
}
func (m *SetUpPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUpPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUpPeerRequest proto.InternalMessageInfo

func (m *SetUpPeerRequest) GetStellarAddress() string {
	if m != nil {
		return m.StellarAddress
	}
	return ""
}

type SetUpPeerResponse struct {
	Status               SetUpPeerResponse_SetUpStatus `protobuf:"varint,1,opt,name=status,proto3,enum=SetUpPeerResponse_SetUpStatus" json:"status,omitempty"`
	TransactionXdr       string                        `protobuf:"bytes,2,opt,name=transactionXdr,proto3" json:"transactionXdr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SetUpPeerResponse) Reset()         { *m = SetUpPeerResponse{} }
func (m *SetUpPeerResponse) String() string { return proto.CompactTextString(m) }
func (*SetUpPeerResponse) ProtoMessage()    {}
func (*SetUpPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{1}
}

func (m *SetUpPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUpPeerResponse.Unmarshal(m, b)
}
func (m *SetUpPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUpPeerResponse.Marshal(b, m, deterministic)
}
func (m *SetUpPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUpPeerResponse.Merge(m, src)
}
func (m *SetUpPeerResponse) XXX_Size() int {
	return xxx_messageInfo_SetUpPeerResponse.Size(m)
}
func (m *SetUpPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUpPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUpPeerResponse proto.InternalMessageInfo

func (m *SetUpPeerResponse) GetStatus() SetUpPeerResponse_SetUpStatus {
	if m != nil {
		return m.Status
	}
	return SetUpPeerResponse_PeerAlreadyExists
}

func (m *SetUpPeerResponse) GetTransactionXdr() string {
	if m != nil {
		return m.TransactionXdr
	}
	return ""
}

type CreateOrFundRequest struct {
	TransactionXdr       string   `protobuf:"bytes,1,opt,name=transactionXdr,proto3" json:"transactionXdr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrFundRequest) Reset()         { *m = CreateOrFundRequest{} }
func (m *CreateOrFundRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrFundRequest) ProtoMessage()    {}
func (*CreateOrFundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{2}
}

func (m *CreateOrFundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrFundRequest.Unmarshal(m, b)
}
func (m *CreateOrFundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrFundRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrFundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrFundRequest.Merge(m, src)
}
func (m *CreateOrFundRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrFundRequest.Size(m)
}
func (m *CreateOrFundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrFundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrFundRequest proto.InternalMessageInfo

func (m *CreateOrFundRequest) GetTransactionXdr() string {
	if m != nil {
		return m.TransactionXdr
	}
	return ""
}

type CreateOrFundResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrFundResponse) Reset()         { *m = CreateOrFundResponse{} }
func (m *CreateOrFundResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrFundResponse) ProtoMessage()    {}
func (*CreateOrFundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{3}
}

func (m *CreateOrFundResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrFundResponse.Unmarshal(m, b)
}
func (m *CreateOrFundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrFundResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrFundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrFundResponse.Merge(m, src)
}
func (m *CreateOrFundResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrFundResponse.Size(m)
}
func (m *CreateOrFundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrFundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrFundResponse proto.InternalMessageInfo

func (m *CreateOrFundResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type InitiatePaymentRequest struct {
	FromStellarAddress string  `protobuf:"bytes,1,opt,name=fromStellarAddress,proto3" json:"fromStellarAddress,omitempty"`
	Amount             float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset              string  `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Memo               string  `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	// Types that are valid to be assigned to Destination:
	//	*InitiatePaymentRequest_ToStellarAddress
	//	*InitiatePaymentRequest_PrevTransactionXdr
	Destination          isInitiatePaymentRequest_Destination `protobuf_oneof:"destination"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *InitiatePaymentRequest) Reset()         { *m = InitiatePaymentRequest{} }
func (m *InitiatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*InitiatePaymentRequest) ProtoMessage()    {}
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{4}
}

func (m *InitiatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiatePaymentRequest.Unmarshal(m, b)
}
func (m *InitiatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiatePaymentRequest.Marshal(b, m, deterministic)
}
func (m *InitiatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiatePaymentRequest.Merge(m, src)
}
func (m *InitiatePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_InitiatePaymentRequest.Size(m)
}
func (m *InitiatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitiatePaymentRequest proto.InternalMessageInfo

func (m *InitiatePaymentRequest) GetFromStellarAddress() string {
	if m != nil {
		return m.FromStellarAddress
	}
	return ""
}

func (m *InitiatePaymentRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InitiatePaymentRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *InitiatePaymentRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type isInitiatePaymentRequest_Destination interface {
	isInitiatePaymentRequest_Destination()
}

type InitiatePaymentRequest_ToStellarAddress struct {
	ToStellarAddress string `protobuf:"bytes,5,opt,name=toStellarAddress,proto3,oneof"`
}

type InitiatePaymentRequest_PrevTransactionXdr struct {
	PrevTransactionXdr string `protobuf:"bytes,6,opt,name=prevTransactionXdr,proto3,oneof"`
}

func (*InitiatePaymentRequest_ToStellarAddress) isInitiatePaymentRequest_Destination() {}

func (*InitiatePaymentRequest_PrevTransactionXdr) isInitiatePaymentRequest_Destination() {}

func (m *InitiatePaymentRequest) GetDestination() isInitiatePaymentRequest_Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *InitiatePaymentRequest) GetToStellarAddress() string {
	if x, ok := m.GetDestination().(*InitiatePaymentRequest_ToStellarAddress); ok {
		return x.ToStellarAddress
	}
	return ""
}

func (m *InitiatePaymentRequest) GetPrevTransactionXdr() string {
	if x, ok := m.GetDestination().(*InitiatePaymentRequest_PrevTransactionXdr); ok {
		return x.PrevTransactionXdr
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InitiatePaymentRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InitiatePaymentRequest_ToStellarAddress)(nil),
		(*InitiatePaymentRequest_PrevTransactionXdr)(nil),
	}
}

type InitiatePaymentResponse struct {
	GwPresentTransactionXdr       string   `protobuf:"bytes,1,opt,name=gwPresentTransactionXdr,proto3" json:"gwPresentTransactionXdr,omitempty"`
	GwReimbursementTransactionXdr string   `protobuf:"bytes,2,opt,name=gwReimbursementTransactionXdr,proto3" json:"gwReimbursementTransactionXdr,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *InitiatePaymentResponse) Reset()         { *m = InitiatePaymentResponse{} }
func (m *InitiatePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*InitiatePaymentResponse) ProtoMessage()    {}
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{5}
}

func (m *InitiatePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiatePaymentResponse.Unmarshal(m, b)
}
func (m *InitiatePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiatePaymentResponse.Marshal(b, m, deterministic)
}
func (m *InitiatePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiatePaymentResponse.Merge(m, src)
}
func (m *InitiatePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_InitiatePaymentResponse.Size(m)
}
func (m *InitiatePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiatePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitiatePaymentResponse proto.InternalMessageInfo

func (m *InitiatePaymentResponse) GetGwPresentTransactionXdr() string {
	if m != nil {
		return m.GwPresentTransactionXdr
	}
	return ""
}

func (m *InitiatePaymentResponse) GetGwReimbursementTransactionXdr() string {
	if m != nil {
		return m.GwReimbursementTransactionXdr
	}
	return ""
}

type PaymentCommitRequest struct {
	SignedReimbursementTransactionXdr string   `protobuf:"bytes,1,opt,name=signedReimbursementTransactionXdr,proto3" json:"signedReimbursementTransactionXdr,omitempty"`
	XXX_NoUnkeyedLiteral              struct{} `json:"-"`
	XXX_unrecognized                  []byte   `json:"-"`
	XXX_sizecache                     int32    `json:"-"`
}

func (m *PaymentCommitRequest) Reset()         { *m = PaymentCommitRequest{} }
func (m *PaymentCommitRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentCommitRequest) ProtoMessage()    {}
func (*PaymentCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{6}
}

func (m *PaymentCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCommitRequest.Unmarshal(m, b)
}
func (m *PaymentCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCommitRequest.Marshal(b, m, deterministic)
}
func (m *PaymentCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCommitRequest.Merge(m, src)
}
func (m *PaymentCommitRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentCommitRequest.Size(m)
}
func (m *PaymentCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCommitRequest proto.InternalMessageInfo

func (m *PaymentCommitRequest) GetSignedReimbursementTransactionXdr() string {
	if m != nil {
		return m.SignedReimbursementTransactionXdr
	}
	return ""
}

type PaymentCommitResponse struct {
	SignedDestinationTransactionXdr string   `protobuf:"bytes,1,opt,name=signedDestinationTransactionXdr,proto3" json:"signedDestinationTransactionXdr,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *PaymentCommitResponse) Reset()         { *m = PaymentCommitResponse{} }
func (m *PaymentCommitResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentCommitResponse) ProtoMessage()    {}
func (*PaymentCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{7}
}

func (m *PaymentCommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentCommitResponse.Unmarshal(m, b)
}
func (m *PaymentCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentCommitResponse.Marshal(b, m, deterministic)
}
func (m *PaymentCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentCommitResponse.Merge(m, src)
}
func (m *PaymentCommitResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentCommitResponse.Size(m)
}
func (m *PaymentCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentCommitResponse proto.InternalMessageInfo

func (m *PaymentCommitResponse) GetSignedDestinationTransactionXdr() string {
	if m != nil {
		return m.SignedDestinationTransactionXdr
	}
	return ""
}

type CommandRequest struct {
	CommandType          int32    `protobuf:"varint,1,opt,name=commandType,proto3" json:"commandType,omitempty"`
	CommandBody          string   `protobuf:"bytes,2,opt,name=commandBody,proto3" json:"commandBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{8}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetCommandType() int32 {
	if m != nil {
		return m.CommandType
	}
	return 0
}

func (m *CommandRequest) GetCommandBody() string {
	if m != nil {
		return m.CommandBody
	}
	return ""
}

type CommandReply struct {
	ResponseBody         string   `protobuf:"bytes,1,opt,name=responseBody,proto3" json:"responseBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandReply) Reset()         { *m = CommandReply{} }
func (m *CommandReply) String() string { return proto.CompactTextString(m) }
func (*CommandReply) ProtoMessage()    {}
func (*CommandReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{9}
}

func (m *CommandReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandReply.Unmarshal(m, b)
}
func (m *CommandReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandReply.Marshal(b, m, deterministic)
}
func (m *CommandReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandReply.Merge(m, src)
}
func (m *CommandReply) XXX_Size() int {
	return xxx_messageInfo_CommandReply.Size(m)
}
func (m *CommandReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommandReply proto.InternalMessageInfo

func (m *CommandReply) GetResponseBody() string {
	if m != nil {
		return m.ResponseBody
	}
	return ""
}

type PaymentRequest struct {
	RouteAddresses       []string `protobuf:"bytes,1,rep,name=routeAddresses,proto3" json:"routeAddresses,omitempty"`
	ServiceSessionId     string   `protobuf:"bytes,2,opt,name=serviceSessionId,proto3" json:"serviceSessionId,omitempty"`
	ServiceRef           string   `protobuf:"bytes,3,opt,name=serviceRef,proto3" json:"serviceRef,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	TransactionAmount    uint32   `protobuf:"varint,5,opt,name=transactionAmount,proto3" json:"transactionAmount,omitempty"`
	Asset                string   `protobuf:"bytes,6,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{10}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetRouteAddresses() []string {
	if m != nil {
		return m.RouteAddresses
	}
	return nil
}

func (m *PaymentRequest) GetServiceSessionId() string {
	if m != nil {
		return m.ServiceSessionId
	}
	return ""
}

func (m *PaymentRequest) GetServiceRef() string {
	if m != nil {
		return m.ServiceRef
	}
	return ""
}

func (m *PaymentRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PaymentRequest) GetTransactionAmount() uint32 {
	if m != nil {
		return m.TransactionAmount
	}
	return 0
}

func (m *PaymentRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type PaymentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentReply) Reset()         { *m = PaymentReply{} }
func (m *PaymentReply) String() string { return proto.CompactTextString(m) }
func (*PaymentReply) ProtoMessage()    {}
func (*PaymentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f2b54376d4c2332, []int{11}
}

func (m *PaymentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentReply.Unmarshal(m, b)
}
func (m *PaymentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentReply.Marshal(b, m, deterministic)
}
func (m *PaymentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentReply.Merge(m, src)
}
func (m *PaymentReply) XXX_Size() int {
	return xxx_messageInfo_PaymentReply.Size(m)
}
func (m *PaymentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentReply.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentReply proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("SetUpPeerResponse_SetUpStatus", SetUpPeerResponse_SetUpStatus_name, SetUpPeerResponse_SetUpStatus_value)
	proto.RegisterType((*SetUpPeerRequest)(nil), "SetUpPeerRequest")
	proto.RegisterType((*SetUpPeerResponse)(nil), "SetUpPeerResponse")
	proto.RegisterType((*CreateOrFundRequest)(nil), "CreateOrFundRequest")
	proto.RegisterType((*CreateOrFundResponse)(nil), "CreateOrFundResponse")
	proto.RegisterType((*InitiatePaymentRequest)(nil), "InitiatePaymentRequest")
	proto.RegisterType((*InitiatePaymentResponse)(nil), "InitiatePaymentResponse")
	proto.RegisterType((*PaymentCommitRequest)(nil), "PaymentCommitRequest")
	proto.RegisterType((*PaymentCommitResponse)(nil), "PaymentCommitResponse")
	proto.RegisterType((*CommandRequest)(nil), "CommandRequest")
	proto.RegisterType((*CommandReply)(nil), "CommandReply")
	proto.RegisterType((*PaymentRequest)(nil), "PaymentRequest")
	proto.RegisterType((*PaymentReply)(nil), "PaymentReply")
}

func init() { proto.RegisterFile("ppsidechannel.proto", fileDescriptor_8f2b54376d4c2332) }

var fileDescriptor_8f2b54376d4c2332 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0x66, 0xf9, 0xa9, 0x72, 0x68, 0x4b, 0x3b, 0xb4, 0xd0, 0xd4, 0x08, 0xb8, 0x17, 0xc4, 0x18,
	0xb2, 0x21, 0x35, 0x31, 0x46, 0xa3, 0x09, 0x50, 0x15, 0x12, 0x12, 0x37, 0xdb, 0x92, 0x78, 0x3b,
	0xec, 0x1e, 0xea, 0x24, 0xdd, 0x1f, 0x67, 0xa6, 0xe0, 0xbe, 0x80, 0xef, 0xe0, 0xab, 0x79, 0xe9,
	0x5b, 0x78, 0x67, 0x66, 0x77, 0x5a, 0xa6, 0xdb, 0x05, 0xee, 0x76, 0xbe, 0xf3, 0x7f, 0xce, 0x77,
	0xce, 0xc2, 0x56, 0x92, 0x08, 0x16, 0xa0, 0xff, 0x9d, 0x46, 0x11, 0x8e, 0x9d, 0x84, 0xc7, 0x32,
	0xb6, 0xdf, 0x41, 0x63, 0x80, 0xf2, 0x32, 0x71, 0x11, 0xb9, 0x87, 0x3f, 0x26, 0x28, 0x24, 0x39,
	0x80, 0xba, 0x90, 0x38, 0x1e, 0x53, 0x7e, 0x1c, 0x04, 0x1c, 0x85, 0xe8, 0x58, 0xfb, 0xd6, 0xcb,
	0x75, 0xaf, 0x80, 0xda, 0x7f, 0x2c, 0x68, 0x1a, 0xc6, 0x22, 0x89, 0x23, 0x81, 0xe4, 0x0d, 0x54,
	0x84, 0xa4, 0x72, 0x92, 0x5b, 0xd5, 0x7b, 0xbb, 0xce, 0x82, 0x4e, 0x8e, 0x0c, 0x32, 0x2d, 0x4f,
	0x6b, 0xab, 0xa8, 0x92, 0xd3, 0x48, 0x50, 0x5f, 0xb2, 0x38, 0xfa, 0x16, 0xf0, 0xce, 0x72, 0x1e,
	0x75, 0x1e, 0xb5, 0x11, 0x36, 0x0c, 0x73, 0xd2, 0x86, 0xa6, 0x72, 0x7d, 0x3c, 0xe6, 0x48, 0x83,
	0xf4, 0xd3, 0x4f, 0x26, 0xa4, 0x68, 0x2c, 0x91, 0x3d, 0x78, 0x96, 0xc1, 0xbe, 0x1f, 0x4f, 0x22,
	0x79, 0xca, 0x91, 0x2a, 0x7b, 0x55, 0x21, 0xe3, 0x18, 0x34, 0x2c, 0xb2, 0x0b, 0x5d, 0x43, 0xe1,
	0xf3, 0x24, 0x0a, 0x58, 0x34, 0x9a, 0xc9, 0x97, 0xed, 0x0f, 0xb0, 0x95, 0x59, 0xe1, 0x57, 0xae,
	0x84, 0x46, 0x6f, 0x0a, 0x59, 0x5a, 0xa5, 0x59, 0x1e, 0x41, 0x6b, 0xde, 0x5c, 0x77, 0xa7, 0x03,
	0x4f, 0xc4, 0xc4, 0xf7, 0xa7, 0x4d, 0x7d, 0xea, 0x4d, 0x9f, 0xf6, 0x3f, 0x0b, 0xb6, 0xcf, 0x23,
	0x26, 0x19, 0x95, 0xe8, 0xd2, 0x34, 0xc4, 0x48, 0x4e, 0x83, 0x3a, 0x40, 0xae, 0x79, 0x1c, 0x0e,
	0xca, 0x86, 0x52, 0x22, 0x21, 0xdb, 0x50, 0xa1, 0xa1, 0x2a, 0x2b, 0x6b, 0xa1, 0xe5, 0xe9, 0x17,
	0x69, 0xc1, 0x1a, 0x15, 0x02, 0x65, 0x67, 0x25, 0x33, 0xcd, 0x1f, 0x84, 0xc0, 0x6a, 0x88, 0x61,
	0xdc, 0x59, 0xcd, 0xc0, 0xec, 0x9b, 0x1c, 0x42, 0x43, 0xc6, 0x85, 0x78, 0x6b, 0x4a, 0x7e, 0xb6,
	0xe4, 0x2d, 0x48, 0xc8, 0x11, 0x90, 0x84, 0xe3, 0xcd, 0x70, 0xbe, 0x31, 0x15, 0xad, 0x5f, 0x22,
	0x3b, 0xa9, 0xc1, 0x46, 0x80, 0x42, 0xb2, 0x28, 0x1b, 0x8b, 0xfd, 0xdb, 0x82, 0x9d, 0x85, 0xda,
	0x75, 0xc7, 0xde, 0xc2, 0xce, 0xe8, 0xd6, 0xe5, 0x28, 0x30, 0x92, 0xc3, 0xb2, 0xd6, 0xdf, 0x27,
	0x26, 0x7d, 0x78, 0x3e, 0xba, 0xf5, 0x90, 0x85, 0x57, 0x13, 0x2e, 0x30, 0x5c, 0xb4, 0xcf, 0x09,
	0xf6, 0xb0, 0x92, 0x1d, 0x40, 0x4b, 0xa7, 0x74, 0x1a, 0x87, 0x21, 0x9b, 0x0d, 0xe5, 0x02, 0x5e,
	0x08, 0x36, 0x8a, 0x30, 0x78, 0x28, 0x42, 0x9e, 0xe1, 0xe3, 0x8a, 0x36, 0x85, 0x76, 0x21, 0x8a,
	0x2e, 0xff, 0x0c, 0xf6, 0x72, 0xeb, 0xfe, 0x5d, 0xbf, 0x4a, 0x83, 0x3c, 0xa6, 0x66, 0x0f, 0xa1,
	0xae, 0x7c, 0xd3, 0x3b, 0x32, 0xef, 0xc3, 0x86, 0x9f, 0x23, 0xc3, 0x34, 0xc1, 0xcc, 0xcf, 0x9a,
	0x67, 0x42, 0x86, 0xc6, 0x49, 0x1c, 0xa4, 0xba, 0x61, 0x26, 0x64, 0xf7, 0xa0, 0x3a, 0xf3, 0x9a,
	0x8c, 0x53, 0x62, 0x43, 0x95, 0xeb, 0xdc, 0x33, 0x93, 0x3c, 0xb9, 0x39, 0xcc, 0xfe, 0x6b, 0x41,
	0xbd, 0x40, 0xf1, 0x03, 0xa8, 0xf3, 0x78, 0x22, 0x51, 0x53, 0x0a, 0x15, 0xbd, 0x57, 0xd4, 0x5e,
	0xcd, 0xa3, 0xe4, 0x15, 0x34, 0x04, 0xf2, 0x1b, 0xe6, 0xe3, 0x00, 0x85, 0x60, 0x71, 0x74, 0x1e,
	0xe8, 0xac, 0x16, 0x70, 0xb2, 0x0b, 0xa0, 0x31, 0x0f, 0xaf, 0x35, 0xe7, 0x0d, 0x44, 0xed, 0x22,
	0xd5, 0xdc, 0xce, 0xb9, 0x3f, 0x7d, 0x92, 0x43, 0x68, 0x1a, 0xfb, 0x7c, 0x9c, 0xef, 0x92, 0xe2,
	0x7f, 0xcd, 0x5b, 0x14, 0xdc, 0xad, 0x55, 0xc5, 0x58, 0x2b, 0xbb, 0x0e, 0xd5, 0x59, 0x8d, 0xc9,
	0x38, 0xed, 0xfd, 0x5a, 0x86, 0x9a, 0xeb, 0x0e, 0x58, 0x80, 0xa7, 0xf9, 0x05, 0x26, 0x3d, 0x58,
	0x9f, 0x9d, 0x46, 0xd2, 0x74, 0x8a, 0x77, 0xb8, 0x4b, 0x16, 0x2f, 0x27, 0x79, 0x0f, 0x55, 0xf3,
	0xae, 0x90, 0x96, 0x53, 0x72, 0xa5, 0xba, 0x6d, 0xa7, 0xf4, 0xf8, 0xf4, 0x61, 0xb3, 0xb0, 0x65,
	0x64, 0xc7, 0x29, 0xbf, 0x39, 0xdd, 0x8e, 0x73, 0xdf, 0x42, 0x7e, 0x84, 0xda, 0x1c, 0x55, 0x49,
	0xdb, 0x29, 0x5b, 0x90, 0xee, 0xb6, 0x53, 0xca, 0xe8, 0xde, 0x05, 0x74, 0x5c, 0x57, 0x8b, 0x2e,
	0x25, 0x1b, 0x33, 0x99, 0x0e, 0xf2, 0xa1, 0xa8, 0x4b, 0x52, 0x77, 0x79, 0xac, 0xee, 0xa1, 0x26,
	0x15, 0xd9, 0x74, 0xe6, 0x49, 0xdb, 0xad, 0x39, 0x26, 0xdf, 0x7a, 0x7d, 0x68, 0xcc, 0xbc, 0x7d,
	0xa1, 0x12, 0x6f, 0x69, 0x6a, 0x78, 0x99, 0x96, 0xb9, 0xe9, 0x14, 0xca, 0xab, 0x39, 0xe6, 0x70,
	0xae, 0x2a, 0xd9, 0xdf, 0xf0, 0xf5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x13, 0x3c, 0xc1,
	0x24, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PPSideChannelClient is the client API for PPSideChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PPSideChannelClient interface {
	SetUpPeer(ctx context.Context, in *SetUpPeerRequest, opts ...grpc.CallOption) (*SetUpPeerResponse, error)
	CreateOrFund(ctx context.Context, in *CreateOrFundRequest, opts ...grpc.CallOption) (*CreateOrFundResponse, error)
	InitiatePayment(ctx context.Context, in *InitiatePaymentRequest, opts ...grpc.CallOption) (*InitiatePaymentResponse, error)
	PaymentCommit(ctx context.Context, in *PaymentCommitRequest, opts ...grpc.CallOption) (*PaymentCommitResponse, error)
}

type pPSideChannelClient struct {
	cc *grpc.ClientConn
}

func NewPPSideChannelClient(cc *grpc.ClientConn) PPSideChannelClient {
	return &pPSideChannelClient{cc}
}

func (c *pPSideChannelClient) SetUpPeer(ctx context.Context, in *SetUpPeerRequest, opts ...grpc.CallOption) (*SetUpPeerResponse, error) {
	out := new(SetUpPeerResponse)
	err := c.cc.Invoke(ctx, "/PPSideChannel/SetUpPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pPSideChannelClient) CreateOrFund(ctx context.Context, in *CreateOrFundRequest, opts ...grpc.CallOption) (*CreateOrFundResponse, error) {
	out := new(CreateOrFundResponse)
	err := c.cc.Invoke(ctx, "/PPSideChannel/CreateOrFund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pPSideChannelClient) InitiatePayment(ctx context.Context, in *InitiatePaymentRequest, opts ...grpc.CallOption) (*InitiatePaymentResponse, error) {
	out := new(InitiatePaymentResponse)
	err := c.cc.Invoke(ctx, "/PPSideChannel/InitiatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pPSideChannelClient) PaymentCommit(ctx context.Context, in *PaymentCommitRequest, opts ...grpc.CallOption) (*PaymentCommitResponse, error) {
	out := new(PaymentCommitResponse)
	err := c.cc.Invoke(ctx, "/PPSideChannel/PaymentCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PPSideChannelServer is the server API for PPSideChannel service.
type PPSideChannelServer interface {
	SetUpPeer(context.Context, *SetUpPeerRequest) (*SetUpPeerResponse, error)
	CreateOrFund(context.Context, *CreateOrFundRequest) (*CreateOrFundResponse, error)
	InitiatePayment(context.Context, *InitiatePaymentRequest) (*InitiatePaymentResponse, error)
	PaymentCommit(context.Context, *PaymentCommitRequest) (*PaymentCommitResponse, error)
}

// UnimplementedPPSideChannelServer can be embedded to have forward compatible implementations.
type UnimplementedPPSideChannelServer struct {
}

func (*UnimplementedPPSideChannelServer) SetUpPeer(ctx context.Context, req *SetUpPeerRequest) (*SetUpPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUpPeer not implemented")
}
func (*UnimplementedPPSideChannelServer) CreateOrFund(ctx context.Context, req *CreateOrFundRequest) (*CreateOrFundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrFund not implemented")
}
func (*UnimplementedPPSideChannelServer) InitiatePayment(ctx context.Context, req *InitiatePaymentRequest) (*InitiatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (*UnimplementedPPSideChannelServer) PaymentCommit(ctx context.Context, req *PaymentCommitRequest) (*PaymentCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentCommit not implemented")
}

func RegisterPPSideChannelServer(s *grpc.Server, srv PPSideChannelServer) {
	s.RegisterService(&_PPSideChannel_serviceDesc, srv)
}

func _PPSideChannel_SetUpPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUpPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPSideChannelServer).SetUpPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPSideChannel/SetUpPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPSideChannelServer).SetUpPeer(ctx, req.(*SetUpPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PPSideChannel_CreateOrFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPSideChannelServer).CreateOrFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPSideChannel/CreateOrFund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPSideChannelServer).CreateOrFund(ctx, req.(*CreateOrFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PPSideChannel_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPSideChannelServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPSideChannel/InitiatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPSideChannelServer).InitiatePayment(ctx, req.(*InitiatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PPSideChannel_PaymentCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPSideChannelServer).PaymentCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPSideChannel/PaymentCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPSideChannelServer).PaymentCommit(ctx, req.(*PaymentCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PPSideChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PPSideChannel",
	HandlerType: (*PPSideChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUpPeer",
			Handler:    _PPSideChannel_SetUpPeer_Handler,
		},
		{
			MethodName: "CreateOrFund",
			Handler:    _PPSideChannel_CreateOrFund_Handler,
		},
		{
			MethodName: "InitiatePayment",
			Handler:    _PPSideChannel_InitiatePayment_Handler,
		},
		{
			MethodName: "PaymentCommit",
			Handler:    _PPSideChannel_PaymentCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ppsidechannel.proto",
}

// PPPaymentUtilityServicesClient is the client API for PPPaymentUtilityServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PPPaymentUtilityServicesClient interface {
	ProcessCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandReply, error)
}

type pPPaymentUtilityServicesClient struct {
	cc *grpc.ClientConn
}

func NewPPPaymentUtilityServicesClient(cc *grpc.ClientConn) PPPaymentUtilityServicesClient {
	return &pPPaymentUtilityServicesClient{cc}
}

func (c *pPPaymentUtilityServicesClient) ProcessCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandReply, error) {
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, "/PPPaymentUtilityServices/ProcessCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PPPaymentUtilityServicesServer is the server API for PPPaymentUtilityServices service.
type PPPaymentUtilityServicesServer interface {
	ProcessCommand(context.Context, *CommandRequest) (*CommandReply, error)
}

// UnimplementedPPPaymentUtilityServicesServer can be embedded to have forward compatible implementations.
type UnimplementedPPPaymentUtilityServicesServer struct {
}

func (*UnimplementedPPPaymentUtilityServicesServer) ProcessCommand(ctx context.Context, req *CommandRequest) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessCommand not implemented")
}

func RegisterPPPaymentUtilityServicesServer(s *grpc.Server, srv PPPaymentUtilityServicesServer) {
	s.RegisterService(&_PPPaymentUtilityServices_serviceDesc, srv)
}

func _PPPaymentUtilityServices_ProcessCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPPaymentUtilityServicesServer).ProcessCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPPaymentUtilityServices/ProcessCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPPaymentUtilityServicesServer).ProcessCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PPPaymentUtilityServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PPPaymentUtilityServices",
	HandlerType: (*PPPaymentUtilityServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessCommand",
			Handler:    _PPPaymentUtilityServices_ProcessCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ppsidechannel.proto",
}

// PPPaymentGatewayClient is the client API for PPPaymentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PPPaymentGatewayClient interface {
	ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentReply, error)
}

type pPPaymentGatewayClient struct {
	cc *grpc.ClientConn
}

func NewPPPaymentGatewayClient(cc *grpc.ClientConn) PPPaymentGatewayClient {
	return &pPPaymentGatewayClient{cc}
}

func (c *pPPaymentGatewayClient) ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentReply, error) {
	out := new(PaymentReply)
	err := c.cc.Invoke(ctx, "/PPPaymentGateway/ProcessPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PPPaymentGatewayServer is the server API for PPPaymentGateway service.
type PPPaymentGatewayServer interface {
	ProcessPayment(context.Context, *PaymentRequest) (*PaymentReply, error)
}

// UnimplementedPPPaymentGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedPPPaymentGatewayServer struct {
}

func (*UnimplementedPPPaymentGatewayServer) ProcessPayment(ctx context.Context, req *PaymentRequest) (*PaymentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPayment not implemented")
}

func RegisterPPPaymentGatewayServer(s *grpc.Server, srv PPPaymentGatewayServer) {
	s.RegisterService(&_PPPaymentGateway_serviceDesc, srv)
}

func _PPPaymentGateway_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PPPaymentGatewayServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PPPaymentGateway/ProcessPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PPPaymentGatewayServer).ProcessPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PPPaymentGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PPPaymentGateway",
	HandlerType: (*PPPaymentGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPayment",
			Handler:    _PPPaymentGateway_ProcessPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ppsidechannel.proto",
}
